vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        pictures:
            uri_prefix: /pictures
            upload_destination: 'aws.storage'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
